### ISSUE TITLE
Basic Authorization Header

### ISSUE THREAD

**Issue by Karthi-SRV** [BGLCorp/API#6]
By using Basic Authorization Header, 

I try to get funding list, but it's said 'access_denied' as a response. Why it's won't work using base Auth.

While I proceed using oauth it works fine.
![screen shot 2017-03-27 at 2 50 38 pm](https://cloud.githubusercontent.com/assets/15937762/24349470/cbdb22c0-12fc-11e7-9448-ea13981674dd.png)

https://api-staging.bgl360.com.au/fund/list.xml?

**Comment by sshanmugalingm** [comment]
May I know which Organization you are representing?

**Comment by Karthi-SRV** [comment]
May I know which Organization you are representing?

The Organization  that I am representing are Limeactuarial.



*Regards,*

*Karthi M.*

*Tiruppur.*

**Comment by sshanmugalingm** [comment]
Are you planning to use the BGL API
